export enum paginationIncrementTypes {
  INCREMENT_PAGINATION_ACTION = "INCREMENT_PAGINATION_ACTIOMT",
  INCREMENT_PAGINATION_SUCCESS = "INCREMENT_PAGINATION_SUCCESS",
  INCREMENT_PAGINATION_FAILURE = "INCREMENT_PAGINATION_FAILURE",
}

export enum paginationDecrementTypes {
  DECREMENT_PAGINATION_ACTION = "DECREMENT_PAGINATION_ACTION",
  DECREMENT_PAGINATION_SUCCESS = "DECREMENT_PAGINATION_SUCCESS",
  DECREMENT_PAGINATION_FAILURE = "DECREMENT_PAGINATION_FAILURE",
}



