export enum paginationTypes {
  INCREMENT_PAGINATION_ACTION = "INCREMENT_PAGINATION_ACTIOMT",
  INCREMENT_PAGINATION_SUCCESS = "INCREMENT_PAGINATION_SUCCESS",
  INCREMENT_PAGINATION_FAILURE = "INCREMENT_PAGINATION_FAILURE",
}
