export enum postTypes {
  FETCH_POST_REQUEST = "FETCH_POST_REQUEST",
  FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS",
  FETCH_POST_FAILURE = "FETCH_POST_FAILURE",
  FETCH_POST_BY_ID_REQUEST = "FETCH_POST_BY_ID_REQUEST",
  FETCH_POST_BY_ID_SUCCESS = "FETCH_POST_BY_ID_SUCCESS",
  FETCH_POST_BY_ID_FAILURE = "FETCH_POST_BY_ID_FAILURE",
}
